### ISSUE TITLE
ClassCastException at random time?

### ISSUE THREAD

**Issue by realkarmakun** [schematico/trevor#15]
After running trevor for a while (1700+ players, Velocity). Getting this error for some players. Can't quite understand what it's about. Maybe pool is too small?
```
[19:59:48 INFO]: [connected player] MakS_na_priKole (/217.66.156.235:5566) has connected
[19:59:48 ERROR]: Some errors occurred whilst posting event LoginEvent{player=[connected player] MakS_na_priKole (/217.66.156.235:5566), result=allowed}.
[19:59:48 ERROR]: #1: 

java.util.concurrent.CompletionException: java.lang.ClassCastException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137) ~[?:?]
        at co.schemati.trevor.common.database.redis.RedisDatabase.lambda$open$0(RedisDatabase.java:75) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.ClassCastException
```

**Comment by realkarmakun** [comment]
```
[09:47:41] [Netty epoll Worker #13/INFO]: [connected player] M41 (/95.133.137.187:50097) has connected
[09:47:41] [Velocity Event Executor - #1/ERROR]: Some errors occurred whilst posting event LoginEvent{player=[connected player] M41 (/95.133.137.187:50097), result=allowed}.
[09:47:41] [Velocity Event Executor - #1/ERROR]: #1: 

java.util.concurrent.CompletionException: java.lang.ClassCastException: class java.lang.Long cannot be cast to class [B (java.lang.Long and [B are in module java.base of loader 'bootstrap')
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137) ~[?:?]
	at co.schemati.trevor.common.database.redis.RedisDatabase.lambda$open$0(RedisDatabase.java:75) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.ClassCastException: class java.lang.Long cannot be cast to class [B (java.lang.Long and [B are in module java.base of loader 'bootstrap')
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:201) ~[?:?]
	at redis.clients.jedis.Jedis.hmset(Jedis.java:813) ~[?:?]
	at co.schemati.trevor.common.database.redis.RedisConnection.create(RedisConnection.java:75) ~[?:?]
	at co.schemati.trevor.common.proxy.DatabaseProxyImpl.lambda$onPlayerConnect$0(DatabaseProxyImpl.java:47) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642) ~[?:?]
	... 9 more
```

**Comment by realkarmakun** [comment]
Alright, probably related issue https://github.com/redis/jedis/issues/122

**Comment by realkarmakun** [comment]
Also related but a bit more fresh https://github.com/redis/jedis/issues/186

**Comment by realkarmakun** [comment]
So after some research this issue appears when someone trying to to something with broken connections. Can it be related to executor service having 8 hardcoded?
https://github.com/schematico/trevor/blob/ab8194c352474930086090d57953df1a11e891de/common/src/main/java/co/schemati/trevor/common/database/redis/RedisDatabase.java#L44
 Maybe trevor just can't handle amount of players because of small thread pool. Which results in some kind of race condition. Right now testing this theory with 1 thread in executor service and 100 players.
